# Generated by Django 4.0.3 on 2022-03-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('total_number_of_rooms', models.IntegerField()),
                ('number_of_rooms_available', models.IntegerField()),
                ('website_url', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
